export const products = [
    {
        id: 0,
        name: 'Hand Bag',
        price: 39.99,
        description: 'Stylish leather handbag for everyday use.',
        instock: 7,
        imgSrc: 'bag1.jpg',
    },
    {
        id: 1,
        name: 'Trench Coat',
        price: 89.99,
        description: 'Classic long trench coat for all seasons.',
        instock: 3,
        imgSrc: 'f1.jpg',
    },
    {
        id: 2,
        name: 'Hand Bag',
        price: 34.50,
        description: 'Compact shoulder bag with modern design.',
        instock: 5,
        imgSrc: 'f3.jpg',
    },
    {
        id: 3,
        name: 'Hoodie',
        price: 49.99,
        description: 'Warm cotton hoodie with soft inner lining.',
        instock: 8,
        imgSrc: 'f4.jpg',
    },
    {
        id: 4,
        name: 'Sneakers',
        price: 59.99,
        description: 'Comfortable sneakers for casual wear.',
        instock: 6,
        imgSrc: 'foot2.jpg',
    },
    {
        id: 5,
        name: 'Sports Shoes',
        price: 64.99,
        description: 'Durable sports shoes with cushioned soles.',
        instock: 4,
        imgSrc: 'foot3.jpg',
    },
    {
        id: 6,
        name: 'Leather Boots',
        price: 84.99,
        description: 'Sturdy leather boots for all-day comfort.',
        instock: 2,
        imgSrc: 'foot4.jpg',
    },
    {
        id: 7,
        name: 'Casual Shoes',
        price: 44.99,
        description: 'Lightweight shoes for everyday walking.',
        instock: 9,
        imgSrc: 'foot5.png',
    },
    {
        id: 8,
        name: 'Jacket',
        price: 109.99,
        description: 'Trendy jacket with a sleek urban fit.',
        instock: 3,
        imgSrc: 'jacket.jpg',
    },
    {
        id: 9,
        name: 'Running Shoes',
        price: 69.99,
        description: 'Breathable running shoes with flexible grip.',
        instock: 10,
        imgSrc: 'foot6.png',
    },
    {
        id: 10,
        name: 'Formal Shoes',
        price: 74.99,
        description: 'Elegant formal shoes for business and events.',
        instock: 5,
        imgSrc: 'footwear.jpg',
    },
    {
        id: 11,
        name: 'Wrist Watch',
        price: 129.99,
        description: 'Classic wrist watch with leather strap.',
        instock: 2,
        imgSrc: 'watch.jpg',
    },
];
